- hosts: localhost
  vars:
    dbuser: root
    dbpass: B!ll3t2012
    dbname: demo
    vpc_nsg: sg-023a6c7237aabe253
  tasks:
  - name: create Mysql RDS instance 
    rds_instance:
      region: us-east-1
      vpc_security_group_ids: "{{ vpc_nsg }}"
      engine: MySQL
      db_instance_identifier: demo
      instance_type: db.t2.small
      password: "{{ dbpass }}"
      username: "{{ dbuser }}"
      allocated_storage: 20
    register: rds
  - debug: var=rds

  - name: Create a new database for the application
    mysql_db:
      name: "{{ dbname }}"
      state: present
      login_host: "{{ rds.endpoint.address }}"
      login_password: "{{ dbpass }}"
      login_user: "{{ dbuser }}"

  - name: Save RDS access to  a file
    copy: 
      dest: ./files/credentials.json 
      content: |
        {
          "dbhost": "{{ rds.endpoint.address }}",
          "dbpass": "{{ dbpass }}",
          "dbuser": "{{ dbuser }}",
          "dbport": 3306,
          "dbname": "{{ dbname }}"
        }
