- hosts: all
  become: true
  vars:
    dbcredentials: "{{  lookup('file', '/tmp/credentials.json') | from_json  }}"
    infonetworks: "{{  lookup('file', './infonetwork.json') | from_json  }}"   

  tasks:
  - include: ./task/installreq.yml
  - include: ./task/createdb.yml
  - include: ./task/app.yml

  
  

 